src/MuyPicky/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from django.conf.urls import url, include
from django.contrib import admin
from restaurant.views import (
        AboutView,
        RestaurantLocationCreateView,
        ContactView,
        CreatorView,
        Creator_2_View,
        )

from menu.views import HomeView

from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(), name = 'login'),
    url(r'^logout/', LogoutView.as_view(), name = 'logout'),
    url(r'^$', HomeView.as_view(), name = 'home'),
    url(r'^register/$', RegisterView.as_view(), name = 'register'),
    url(r'^about/$', AboutView.as_view(), name = 'about'),
    url(r'^contact/$', ContactView.as_view(), name = 'contact'),
    url(r'^creator/$', CreatorView.as_view(), name = 'divya'),    
    url(r'^creator2/$', Creator_2_View.as_view(), name = 'harsha'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name = 'follow'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name = 'activate'),

    url(r'^restaurant/', include('restaurant.urls', namespace = 'restaurant')),
    url(r'^item/', include('menu.urls', namespace = 'item')),
    url(r'^u/', include('profiles.urls', namespace = 'profile')),
    ]

src/menu/urls.py
from django.conf.urls import url

from .views import (
        ItemListView,
        ItemDetailView,
        ItemCreateView,
        ItemUpdateView,
    )

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name = 'create'),
    # url(r'^(?P<pk>\d+)/update/$', ItemUpdateView.as_view(), name = 'update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name = 'detail'),
    url(r'^$', ItemListView.as_view(), name='list'),
]

src/menu/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

from restaurant.models import RestaurantLocation
# Create your models here.

class Item(models.Model):
	# Associations
	user 			= models.ForeignKey(settings.AUTH_USER_MODEL)
	restaurant		= models.ForeignKey(RestaurantLocation)

	# Actual Fields
	name			= models.CharField(max_length = 120)
	contents		= models.TextField(help_text = 'Seperate values by comma')
	excludes		= models.TextField(blank = True, null = True, help_text = 'Seperate values by comma')
	public			= models.BooleanField(default = True)
	timestamp 		= models.DateTimeField(auto_now_add = True)
	updated			= models.DateTimeField(auto_now = True)

	class Meta:
		ordering = ['-updated', '-timestamp']

	def get_contents(self):
		contents = self.contents.split(",")

		for i in range(len(contents)):
			contents[i] = contents[i].lower()

		return contents
		
	def get_excludes(self):
		return self.excludes.split(",")


	def get_absolute_url(self):
		return reverse('item:detail', kwargs={'pk' : self.pk})


	def get_absolute_update(self):
		return reverse('item:update', kwargs={'pk' : self.pk})

	def __str__(self):
		return self.name

src/menu/forms.py
from django.forms import ModelForm
from .models import Item
from restaurant.models import RestaurantLocation

class ItemForm(ModelForm):
	class Meta:
		model = Item

		fields = [
			'name',
			'restaurant',
			'contents',
			'excludes',
			'public'
		]


	def __init__(self, user = None, **kwargs):
		super(ItemForm, self).__init__(**kwargs)
		self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner = user)

src/menu/views.py
from .forms import ItemForm
from .models import Item
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your views here.

class HomeView(View):
	def get(self, request, **kwargs):
		if not request.user.is_authenticated():
			return render(request, "home.html", {})

		user = request.user

		is_following_user_ids = [x.user.id for x in user.is_following.all()]
		qs = Item.objects.filter(user__id__in = is_following_user_ids, public = True).order_by("user")

		user_ = False
		
		if self.request.GET.get("u"):
			searched_ = self.request.GET.get("u")
		
			user_ = User.objects.filter(username__icontains = searched_)

		context = {"object_list" : qs, "user_" : user_}

		return render(request, "menu/home-feed.html", context)

class ItemListView(LoginRequiredMixin, ListView):

	def get_queryset(self):
		print(self.request.user)
		return Item.objects.filter(user = self.request.user)

class ItemDetailView(LoginRequiredMixin, DetailView):
	def get_queryset(self):
		return Item.objects.filter(user = self.request.user)


class ItemCreateView(LoginRequiredMixin, CreateView):
	form_class = ItemForm
	template_name = 'form.html'

	def form_valid(self, form):
		instance = form.save(commit = False)
		instance.user = self.request.user
		return super(ItemCreateView, self).form_valid(form)


	def get_queryset(self):
		return Item.objects.filter(user = self.request.user)


	def get_form_kwargs(self):
		kwargs = super(ItemCreateView, self).get_form_kwargs()
		# kwargs['instance'] = Item.objects.filter(user = self.request.user).first()
		kwargs['user'] = self.request.user
		return kwargs


	def get_context_data(self, **kwargs):
		context = super(ItemCreateView, self).get_context_data(**kwargs)
		context['title'] = 'Add Item'
		return context


class ItemUpdateView(LoginRequiredMixin, UpdateView):
	form_class = ItemForm
	template_name = 'menu/update-detail.html'

	def get_queryset(self):
		return Item.objects.filter(user = self.request.user)


	def get_context_data(self, **kwargs):
		context = super(ItemUpdateView, self).get_context_data(**kwargs)
		context['title'] = 'Update Item'
		return context


	def get_form_kwargs(self):
		kwargs = super(ItemUpdateView, self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

src/templates/menu/home-feed.html
{% extends "base.html" %}
{% block title %}User following feed | MuyPicky.com{% endblock title %}

{% block content %}
<form class="form row" style="width: 50%">

	<input type="text" name="u" placeholder="Search for a user" class = "input-field col-sm-8" value="{{ request.GET.u }}">
	<input type="submit" value="Search" class="input-field waves-effect waves-light btn blue col-sm-3" style="margin-left: 20px">
</form>

{% if user_ %}
	<h3>Results</h3>
	{% for user in user_ %}
		<span class="lead" style="font-size: 150%;"><a href="/u/{{user}}" style="text-decoration: none">{{ user }}</a></span> 
	{% endfor %}
{% elif not request.GET.u %}
{% else %}
<span class="lead">No users found</span>
{% endif %}

	<h1>User following feed</h1>

{% if object_list %}

	<table class="table table-hover table-borderless">
		<thead class="table-primary">
			<tr>
				<td>Item's Name</td>
				<td>Contents</td>
				<td>Excludes</td>
				<td>Following</td>
			</tr>
		</thead>

		<tbody>
			{% for obj in object_list %}
				<tr>	
					<td><a style="text-decoration: none" href="/u/{{obj.user}}?q={{obj.name}}">{{ obj.name }}</a></td>
					<td>{{ obj.contents }}</td>
					{% if obj.excludes %}
						<td>{{ obj.excludes }}</td>
					{% else %}
						<td>None</td>
					{% endif %}
					<td><a href="/u/{{obj.user}}">{{ obj.user }}</a></td>
				</tr>
			{% endfor %}
	</tbody>
	</table>
{% else %}
<h3 class="lead">Nothing to show</h3>
{% endif %}
{% endblock content %}

src/templates/menu/item_detail.html
{% extends "base.html" %}
{% block title %}Menu item | MuyPicky.com{% endblock title %}

{% block content %}
	<h1 class="display-4">{{ object.name }}</h1>
		
	<h3>Location : <small>{{ object.restaurant.name }}</small></h3>	

	<p>{{ object.location }}</p>
	<p>{{ object.timestamp }} , Updated {{ object.updated|timesince }} ago</p><br>

	

{% endblock content %}

src/templates/menu/item_list.html
{% extends "base.html" %}
{% block title %}Menu Items | MuyPicky.com{% endblock title %}

{% block content %}
	<h1>Menu item <small style="font-size: 40%">
		<a href={% url 'item:create' %} style="text-decoration: none">Add one</a></small></h1>
{% if object_list %}
	<table class="table table-hover table-borderless">
		<thead class="table-primary">
			<tr>
				<td>Item's Name</td>
				<td>Contents</td>
				<td>Excludes</td>
			</tr>
		</thead>

		<tbody>
			{% for obj in object_list %}
				<tr>	
					<td><a style="text-decoration: none" href="{{ obj.get_absolute_url }}">{{ obj.name }}</a></td>
					<td>{{ obj.contents }}</td>
					{% if obj.excludes %}
						<td>{{ obj.excludes }}</td>
					{% else %}
						<td>None</td>
					{% endif %}
				</tr>
			{% endfor %}
	</tbody>
	</table>
{% else %}
<span class="lead">Nothing to show</span>
{% endif %}
{% endblock content %}

src/templates/menu/update-detail.html
{% extends "base.html" %}
{% block title %}{{form.instance.name}} | MuyPicky.com{% endblock title %}

{% block content %}
	<h1 class="display-4">{{ form.instance.name }}</h1>
		
	<h3>Location : <small>{{ form.instance.restaurant.name }}</small></h3>	

	<p>{{ form.instance.location }}</p>
	<p>{{ form.instance.timestamp }} , Updated {{ form.instance.updated|timesince }} ago</p><br>

<hr>
<h3>Want to change it?</h3>

{% include 'snippets/form-snippet.html' with form=form %}

{% endblock content %}